#!/bin/bash   
#SBATCH -J incar.batch
#SBATCH -t 250:00:00 
#SBATCH -N 1
#SBATCH -n 16
#SBATCH -o //home/aksenov/Simulation_wrapper/siman2/tests/test1/Na111.8u//incar.batch/sbatch.out
#SBATCH -e //home/aksenov/Simulation_wrapper/siman2/tests/test1/Na111.8u//incar.batch/sbatch.err
#SBATCH --mem-per-cpu=7675
cd //home/aksenov/Simulation_wrapper/siman2/tests/test1/Na111.8u//incar.batch/
export OMP_NUM_THREADS=1
module add prun/1.0
module add intel/16.0.2.181
module add impi/5.1.3.181
touch RUNNING

#sequence set: 1 
cp 1.INCAR  INCAR
#Basic run:
cp 1.POSCAR POSCAR
prun /opt/vasp/bin/vasp5.4.1MPI >incar.batch.1.1.log
sleep 20
mv OUTCAR 1.1.OUTCAR
mv CONTCAR 1.1.CONTCAR
mv CHG 1.1.CHG
gzip -f 1.1.CHG
cp 1.1.CONTCAR POSCAR  #sequence_set: preparation of input geo for next set

#sequence set: 2 
cp 2.INCAR  INCAR
#Basic run:
prun /opt/vasp/bin/vasp5.4.1MPI >incar.batch.1.2.log
sleep 20
mv OUTCAR 1.2.OUTCAR
mv CONTCAR 1.2.CONTCAR
mv CHG 1.2.CHG
gzip -f 1.2.CHG
cp 1.2.CONTCAR POSCAR  #sequence_set: preparation of input geo for next set

#sequence set: 3 
cp 3.INCAR  INCAR
#Basic run:
prun /opt/vasp/bin/vasp5.4.1MPI >incar.batch.1.3.log
sleep 20
mv OUTCAR 1.3.OUTCAR
mv CONTCAR 1.3.CONTCAR
mv CHG 1.3.CHG
gzip -f 1.3.CHG
cp 1.3.CONTCAR POSCAR  #sequence_set: preparation of input geo for next set

#sequence set: 10 
cp 10.INCAR  INCAR
#Basic run:
prun /opt/vasp/bin/vasp5.4.1MPI >incar.batch.1.10.log
sleep 20
mv OUTCAR 1.10.OUTCAR
mv CONTCAR 1.10.CONTCAR
mv CHG 1.10.CHG
gzip -f 1.10.CHG
cp 1.10.CONTCAR POSCAR  #sequence_set: preparation of input geo for next set


#Footer section: 
rm RUNNING
