#!/bin/bash   
#SBATCH -J Li2CoPO4F.static
#SBATCH -t 250:00:00 
#SBATCH -N 1
#SBATCH -n 16
#SBATCH -o /home/aksenov//test//Li2CoPO4F.static/sbatch.out
#SBATCH -e /home/aksenov//test//Li2CoPO4F.static/sbatch.err
#SBATCH --mem-per-cpu=7675
cd /home/aksenov//test//Li2CoPO4F.static/
export OMP_NUM_THREADS=1
module add prun/1.0
module add intel/16.0.2.181
module add impi/5.1.3.181
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/aksenov/tools/lib64:/home/aksenov/tools/atlas
export PATH=$PATH:/home/aksenov/tools
touch RUNNING
#Basic run:
cp 1.POSCAR POSCAR
prun /opt/vasp/bin/vasp5.4.1MPI >Li2CoPO4F.static.1.log
sleep 20
mv OUTCAR 1.OUTCAR
mv CONTCAR 1.CONTCAR
cp CHGCAR 1.CHGCAR
gzip -f 1.CHGCAR
rm WAVECAR  # rm_chg_wav flag

#Footer section: 
rm PROCAR DOSCAR OSZICAR PCDAT REPORT XDATCAR vasprun.xml
rm RUNNING
