#!/bin/bash   
#SBATCH -J Na111.8u
#SBATCH -t 250:00:00 
#SBATCH -N 1
#SBATCH -n 16
#SBATCH -o /home/aksenov/Na/bcc//Na111.8u/sbatch.out
#SBATCH -e /home/aksenov/Na/bcc//Na111.8u/sbatch.err
#SBATCH --mem-per-cpu=7675
#SBATCH --mail-user=d.aksenov@skoltech.ru
#SBATCH --mail-type=END
cd /home/aksenov/Na/bcc//Na111.8u/
export OMP_NUM_THREADS=1
module add prun/1.0
module add intel/16.0.2.181
module add impi/5.1.3.181
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/tools/lib64:~/tools/atlas
export PATH=$PATH:~/tools
#Basic run:
cp 1.POSCAR POSCAR
prun /opt/vasp/bin/vasp5.4.1MPI_aksenov >Na111.8u.1.log
sleep 20
mv OUTCAR 1.OUTCAR
mv CONTCAR 1.CONTCAR
mv CHG 1.CHG
gzip 1.CHG

#Footer section: 
rm PROCAR DOSCAR OSZICAR PCDAT REPORT XDATCAR vasprun.xml
